force-app/main/default/objects/Assignment__c/Assignment__c.object-meta.xml
<CustomObject>
    <description>Junction object for employees/deals</description>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assignment__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <description>Masterdetail relationship (assignment(child) - employee)</description>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Service_Deal__c.field-meta.xml
<CustomField>
    <fullName>Service_Deal__c</fullName>
    <description>Masterdetail relationship (assignment(child) - service deal)</description>
    <label>Service Deal</label>
    <referenceTo>Service_Deal__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Pending</fullName>
                <default>true</default>
                <label>On Pending</label>
            </value>
            <value>
                <fullName>Assigned/In Work</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Workers at the company &quot;Shine Cleaning&quot;</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Deal__c/Service_Deal__c.object-meta.xml
<CustomObject>
    <description>Object for creating deals with customers</description>
    <label>Service Deal</label>
    <nameField>
        <displayFormat>SL-{00000}</displayFormat>
        <label>Deal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Deal__c/fields/Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Close_Date__c</fullName>
    <description>Date and time when cleaning must be done</description>
    <label>Close Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Service_Deal__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Date and time when cleaning starts</description>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ServiceDealEmployeeAssigmentService.cls
public with sharing class ServiceDealEmployeeAssigmentService {
    @AuraEnabled
    public static void addEmployee(Id serviceId) {
        Service_Deal__c serviceDeal = [
            SELECT Id, Start_Date__c, Close_Date__c
            FROM Service_Deal__c
            WHERE Id = :serviceId
            LIMIT 1
        ];

        List<Employee__c> emploees = [
            SELECT
                Id,
                (
                    SELECT Id, Status__c, Service_Deal__c, Service_Deal__r.Start_Date__c, Service_Deal__r.Close_Date__c
                    FROM Assignments__r
                )
            FROM Employee__c
        ];

        Employee__c employeeToAssign = new Employee__c();

        Map<Id, Integer> countOfAssignments = new Map<Id, Integer>();
        Integer minCount = 100000; // зробити присвоєння першого значення з мапи

        List<Employee__c> employeesToRemove = new List<Employee__c>();
        for (Employee__c empl : emploees) {
            for (Assignment__c assignment : empl.Assignments__r) {
                if (
                    assignment.Service_Deal__r.Start_Date__c <= serviceDeal.Close_Date__c &&
                    assignment.Service_Deal__r.Close_Date__c >= serviceDeal.Start_Date__c
                ) {
                    employeesToRemove.add(empl);
                    break;
                }
            }
        }
        for (Integer i = emploees.size() - 1; i >= 0; i--) {
            Employee__c emplToRemove = emploees[i];
            if (employeesToRemove.contains(emplToRemove)) {
                emploees.remove(i);
            }
        }

        for (Employee__c empl : emploees) {
            Integer pendingAssignmentsCount = 0;

            for (Assignment__c assignment : empl.Assignments__r) {
                if (assignment.Status__c == 'On Pending' || assignment.Status__c == 'Assigned/In Work') {
                    pendingAssignmentsCount++;
                }
            }

            countOfAssignments.put(empl.Id, pendingAssignmentsCount);
        }
        system.debug('countOfAssignments ' + countOfAssignments);
        for (Id employeeId : countOfAssignments.keySet()) {
            Integer currentCount = countOfAssignments.get(employeeId);
            if (currentCount < minCount) {
                minCount = currentCount;
                employeeToAssign.Id = employeeId;
            }
        }
        system.debug('employeeToAssign ' + employeeToAssign.Id);
        if (employeeToAssign.Id != null) {
            String name = [SELECT Name FROM Employee__c WHERE Id = :employeeToAssign.Id LIMIT 1].Name;
            Assignment__c newAssignment = new Assignment__c(
                Name = name + ' Auto assigned',
                Employee__c = employeeToAssign.Id,
                Service_Deal__c = serviceDeal.Id,
                Status__c = 'On Pending'
            );
            insert newAssignment;
        } else {
            throw new AuraHandledException('No available employees for this service deal at this time.');
        }
    }
}